class Product{
    id: int
    is_active: bool
    available_quantity: int
    title: str
    subtitle: str
    images: List[Image]
    main_image: Image
    article: str
    description: str
    price: int
    parameters: Dict[str,str]
    category: List[Category]
}

class Image{
    image: byte
}


class Category{
    parent: Category
    image: Image
    icon_name: str
    name: str
}

class Order{
    order_id: int
    creation_datetime: datetime
    customer_name: str
    customer_phone: str
    customer_email:str
    total_price: int
    customer: Customer
    items: List[OrderItem]    
    comment: str
    delivery: Delivery
    completed: bool
}

class Delivery{
    delivery_adress: str
    delivery_type: int
    delivery_price: int

    calculate_price()
}

class SdekDelivery{

}

class OrderSyncService{}

enum DeliveryType{
    sdek
    self_pickup
    delivery
}

class OrderItem{
    amount: int
    product: Product
}

class Calculator{
    calculate()
}



class User{
    role
    orders: List[Order]
}

enum Role{
    Customer
    Admin
}

User --> Role
Product -left-> Category
    Category --> Image
Product *--> Image
Order --> User
Order -left-> Delivery
    Delivery -left-> DeliveryType
    SdekDelivery <|-- Delivery
Order *--> OrderItem
    OrderItem -left-> Product
