start
    :Admin creates Category;


    :Admin creates Product:
    ----
    Admin creates Product template
    Admin fills Product template
    Admin sets Product_isActive
    Admin sets Product_amount
    Admin save Product template;

    :Customer choose category;
    :Customer search Product in catalog;
    if (Customer asure abaut Product) then (yes)
        
    else (no)
        :Customer explore Product
        ----
        Customer click product
        Customer go throu product images;
    endif

    :Customer add Product to buscket;
    :Customer Open Buscket;
    :Customer explore order;
    :Customer change amount of items in order;
    :Customer fills contact details;
    :Customer makes order;

    :Notification sent to Admin;
    :Admin process order;
    :Admin set order status;

end